FROM ruby:3.2.2-slim-bullseye

# Common dependencies
RUN apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  build-essential \
  gnupg2 \
  curl \
  less \
  git \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

# Add PostgreSQL to sources list
RUN echo "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main 16" > /etc/apt/sources.list.d/pgdg.list && \
  curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

RUN apt-get update&& \
  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends  postgresql-client-16 libpq-dev \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/

ENV APP_HOME /rails-app
WORKDIR $APP_HOME
COPY Gemfile $APP_HOME/Gemfile
COPY Gemfile.lock $APP_HOME/Gemfile.lock
RUN bundle install
COPY . $APP_HOME

EXPOSE 3000
ENV LANG=C.UTF-8

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
