version: "3.7"
services:
  x-backend: &backend
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        RUBY_VERSION: "3.2.2"
        PG_MAJOR: "16"
    environment: &env
      # ----
      # Application configuration
      # ----
      ROOT_DIR: "/rails-app/"
      RAILS_ENV: ${RAILS_ENV:-development}
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      REDIS_URL: redis://redis:6379/1
      MALLOC_ARENA_MAX: 2
      WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
      ACTION_CABLE_ADAPTER: ${ACTION_CABLE_ADAPTER:-anycable}
      ANYCABLE_RPC_HOST: 0.0.0.0:50051
      ANYCABLE_BROADCAST_ADAPTER: http
      ANYCABLE_HTTP_BROADCAST_URL: http://ws:8090/_broadcast
      TURBO_RAILS_KEY: turbo_rails_key
      # ----
      # Dev tools
      # ----
      HISTFILE: /usr/local/hist/.bash_history
      IRB_HISTFILE: /usr/local/hist/.irb_history
      PSQL_HISTFILE: /usr/local/hist/.psql_history
      EDITOR: vi
      # -----
      # Caches
      # -----
      BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
      XDG_DATA_HOME: /rails-app/tmp/cache
      # ----
      # Test envs
      CHROME_URL: ${CHROME_URL:-http://chrome:3333}
    tmpfs:
      - /tmp
      - /app/tmp/pids

  db:
    image: "postgres:16.0-alpine3.18"
    volumes:
      - rails-app-postgres-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      PSQL_HISTFILE: /root/log/.psql_history
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  rails:
    <<: *backend
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-app:cached
      - rails-app-cache:/rails-app/tmp/cache
      - rails-app-bundle:/usr/local/bundle
      - rails-app-builds:/rails-app/app/assets/builds
      - rails-app-assets:/app/public/assets
      - rails-app-storage:/rails-app/storage
      - rails-app-history:/usr/local/hist
    ports:
      - 4000:3000
      - 35729:35729
    depends_on:
      maildev:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      ws:
        condition: service_started
  redis:
    image: redis:7.2.1-alpine3.18
    volumes:
      - rails-app-redis:/data
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  ws:
    image: anycable/anycable-go:1.4
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      ANYCABLE_HOST: "0.0.0.0"
      ANYCABLE_PORT: 8080
      ANYCABLE_REDIS_URL: redis://redis:6379/0
      ANYCABLE_RPC_HOST: anycable:50051
      ANYCABLE_DEBUG: 1
      ANYCABLE_TURBO_RAILS_KEY: turbo_rails_key
      ANYCABLE_JWT_ID_KEY: anycable_jwt_key
      ANYCABLE_BROADCAST_ADAPTER: "http"
      ANYCABLE_REDIS_CHANNEL: __anycable__
    depends_on:
      redis:
        condition: service_healthy

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 8025
      MAILDEV_MAIL_DIRECTORY: /home/node/data
    volumes:
      - rails-app-mc-data:/home/node
    ports:
      - "1025:1025"
      - "8025:8025"

  solargraph:
    <<: *backend
    ports:
      - 7658:7658
    volumes:
      - .:/rails-app
      - rails-app-bundle:/usr/local/bundle
    command: ["solargraph", "socket", "stdio"]
    restart: always

  chrome:
    # Currently, Apple M1 is only supported in unnumbered "latest" versions.
    # See https://github.com/browserless/chrome/issues/1393
    image: browserless/chrome:latest
    ports:
      - "3333:3333"
    volumes:
      - .:/rails-app
    environment:
      PORT: 3333
      # Set connection timeout for debugging
      # https://docs.browserless.io/docs/docker.html#connection-timeout
      CONNECTION_TIMEOUT: 600000

volumes:
  rails-app-postgres-db:
  rails-app-redis:
  rails-app-bundle:
  rails-app-cache:
  rails-app-builds:
  rails-app-assets:
  rails-app-storage:
  rails-app-history:
  rails-app-mc-data:
